// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXCCcrgZgxJBsGx9CFUlODwiJjrJg3-_U',
    appId: '1:840595527235:web:d8adc233665d2eba3aa6f6',
    messagingSenderId: '840595527235',
    projectId: 'jesreal-api-store-app',
    authDomain: 'jesreal-api-store-app.firebaseapp.com',
    storageBucket: 'jesreal-api-store-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOi75B6kGt7N5h1BcLkHVFJjqUX_GT3eM',
    appId: '1:840595527235:android:b7e1bfcba348dda83aa6f6',
    messagingSenderId: '840595527235',
    projectId: 'jesreal-api-store-app',
    storageBucket: 'jesreal-api-store-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlTKamr_7ANZw0oZ5kSncKL3NBdR490gk',
    appId: '1:840595527235:ios:fc14db5a1212abc23aa6f6',
    messagingSenderId: '840595527235',
    projectId: 'jesreal-api-store-app',
    storageBucket: 'jesreal-api-store-app.appspot.com',
    iosBundleId: 'com.example.riverpodApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlTKamr_7ANZw0oZ5kSncKL3NBdR490gk',
    appId: '1:840595527235:ios:d8e9fd3d87b94eb13aa6f6',
    messagingSenderId: '840595527235',
    projectId: 'jesreal-api-store-app',
    storageBucket: 'jesreal-api-store-app.appspot.com',
    iosBundleId: 'com.example.riverpodApp.RunnerTests',
  );
}
